### ISSUE TITLE
when build orb-slam3, could not find COLMAP

### ISSUE THREAD

**Issue by Leo-Nebula** [Changfei-Fu/auto_EVO-ORB_SLAM3#1]
CMake Error at CMakeLists.txt:51 (find_package):
  By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "COLMAP", but
  CMake did not find one.

  Could not find a package configuration file provided by "COLMAP" with any
  of the following names:

    COLMAPConfig.cmake
    colmap-config.cmake

  Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set
  "COLMAP_DIR" to a directory containing one of the above files.  If "COLMAP"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by Changfei-Fu** [comment]
you can just delete the contents about colmap in cmakelists.



发自我的iPhone


------------------ Original ------------------
From: Leo-Nebula ***@***.***&gt;
Date: Wed,Apr 6,2022 6:22 PM
To: Changfei-Fu/auto_EVO-ORB_SLAM3 ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Changfei-Fu/auto_EVO-ORB_SLAM3] when build orb-slam3, could not find COLMAP (Issue #1)





 
CMake Error at CMakeLists.txt:51 (find_package):
 By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has
 asked CMake to find a package configuration file provided by "COLMAP", but
 CMake did not find one.
 
Could not find a package configuration file provided by "COLMAP" with any
 of the following names:
 COLMAPConfig.cmake colmap-config.cmake  
Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set
 "COLMAP_DIR" to a directory containing one of the above files.  If "COLMAP"
 provides a separate development package or SDK, be sure it has been
 installed.

**Comment by Changfei-Fu** [comment]
> CMake Error at CMakeLists.txt:51 (find_package): By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "COLMAP", but CMake did not find one.
> 
> Could not find a package configuration file provided by "COLMAP" with any of the following names:
> 
> ```
> COLMAPConfig.cmake
> colmap-config.cmake
> ```
> 
> Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set "COLMAP_DIR" to a directory containing one of the above files. If "COLMAP" provides a separate development package or SDK, be sure it has been installed.

Thank you for your reminder, I have fixed this bug and you can give it try again.
